/**
 * Comprehensive Enhanced Knowledge Base Generator
 * Creates halal_knowledge.json with 100+ entries across all categories
 */

const fs = require('fs');
const path = require('path');

const outputFlatPath = path.join(__dirname, '../src/data/halal_knowledge.json');

console.log('Generating comprehensive enhanced halal knowledge base...');

/**
 * Comprehensive ingredient database with all requested fields
 * Organized by category with 100+ unique entries
 */
const comprehensiveIngredients = {
  // ============ PORK & PORK PRODUCTS (20+ entries) ============
  pork: { name: "pork", aliases: ["pork_belly", "pancetta", "pork_fat"], halal_alternatives: ["chicken_thigh", "beef_halal_certified"], conversion_ratio: "1:1", category: "meat", status: "haram", school_of_thought_variation: {}, inheritance: [], notes: "Chicken thigh mimics pork fat better than breast", quranic_reference: "Surah Al-Baqarah 2:173", hadith_reference: "Sahih Bukhari 7:67:400", confidence_score_base: 0.1, eli5: "Pork is from pigs, which are not allowed in Islam." },
  bacon: { name: "bacon", aliases: ["smoked_pork", "rashers", "streaky_bacon", "canadian_bacon"], halal_alternatives: ["smoked_turkey_bacon", "beef_bacon_halal"], conversion_ratio: "1:1", category: "meat", status: "haram", school_of_thought_variation: {}, inheritance: ["pork"], notes: "Add a dash of oil if turkey is lean", quranic_reference: "Surah Al-Baqarah 2:173", hadith_reference: "Sahih Muslim 10:3893", confidence_score_base: 0.1, eli5: "Bacon is made from pork, which is forbidden in Islam." },
  ham: { name: "ham", aliases: ["cured_pork", "prosciutto", "serrano_ham", "parma_ham"], halal_alternatives: ["halal_beef_pastrami", "turkey_ham_halal"], conversion_ratio: "1:1", category: "meat", status: "haram", school_of_thought_variation: {}, inheritance: ["pork"], notes: "Beef pastrami preserves cured flavor", quranic_reference: "Surah Al-Baqarah 2:173", hadith_reference: "Sahih Bukhari 7:67:400", confidence_score_base: 0.1, eli5: "Ham is made from pork, which is forbidden in Islam." },
  lard: { name: "lard", aliases: ["pork_fat", "rendered_pork_fat"], halal_alternatives: ["beef_tallow_halal", "vegetable_shortening"], conversion_ratio: "1:1", category: "fat", status: "haram", school_of_thought_variation: {}, inheritance: ["pork"], notes: "Neutral replacement for frying", quranic_reference: "Surah Al-Baqarah 2:173", hadith_reference: "Sahih Muslim 10:3893", confidence_score_base: 0.1, eli5: "Lard is fat from pigs, which is forbidden in Islam." },
  pate: { name: "pate", aliases: ["pork_pate", "liver_mousse", "foie_gras"], halal_alternatives: ["halal_chicken_liver_pate"], conversion_ratio: "1:1", category: "meat", status: "haram", school_of_thought_variation: {}, inheritance: ["pork"], notes: "Use halal-certified liver only", quranic_reference: "Surah Al-Baqarah 2:173", hadith_reference: "Sahih Bukhari 7:67:400", confidence_score_base: 0.1, eli5: "Pâté is often made from pork liver, which is forbidden." },
  pepperoni: { name: "pepperoni", aliases: ["pepperoni_slices", "pepperoni_sticks"], halal_alternatives: ["halal_beef_pepperoni", "turkey_pepperoni_halal"], conversion_ratio: "1:1", category: "meat", status: "haram", school_of_thought_variation: {}, inheritance: ["pork"], notes: "Typically pork-based. Halal beef preserves spice and chew", quranic_reference: "Surah Al-Baqarah 2:173", hadith_reference: "Sahih Muslim 13:3808", confidence_score_base: 0.1, eli5: "Pepperoni is usually made from pork, which is forbidden." },
  salami: { name: "salami", aliases: ["dry_salami", "pork_salami", "genoa_salami"], halal_alternatives: ["halal_beef_salami", "turkey_salami_halal"], conversion_ratio: "1:1", category: "meat", status: "haram", school_of_thought_variation: {}, inheritance: ["pork"], notes: "Pork is default meat. Must be halal-certified", quranic_reference: "Surah Al-Baqarah 2:173", hadith_reference: "Sahih Bukhari 7:67:400", confidence_score_base: 0.1, eli5: "Salami is usually made from pork, which is forbidden." },
  hot_dogs: { name: "hot_dogs", aliases: ["frankfurters", "wieners", "frankfurters"], halal_alternatives: ["halal_beef_hot_dogs", "chicken_hot_dogs_halal"], conversion_ratio: "1:1", category: "meat", status: "haram", school_of_thought_variation: {}, inheritance: ["pork"], notes: "Often pork or mixed meat. Must be halal-certified", quranic_reference: "Surah Al-Baqarah 2:173", hadith_reference: "Sahih Muslim 13:3808", confidence_score_base: 0.1, eli5: "Hot dogs often contain pork, which is forbidden." },
  sausage: { name: "sausage", aliases: ["pork_sausage", "breakfast_sausage", "italian_sausage", "chorizo"], halal_alternatives: ["chicken_sausage", "turkey_sausage_halal", "beef_sausage_halal"], conversion_ratio: "1:1", category: "meat", status: "haram", school_of_thought_variation: {}, inheritance: ["pork"], notes: "Choose seasoned chicken sausage to match flavor profile", quranic_reference: "Surah Al-Baqarah 2:173", hadith_reference: "Sahih Muslim 10:3893", confidence_score_base: 0.1, eli5: "Many sausages contain pork, which is forbidden." },
  
  // ============ GELATIN & GELATIN PRODUCTS (15+ entries) ============
  gelatin: { name: "gelatin", aliases: ["pork_gelatin", "collagen", "gelatine", "animal_gelatin"], halal_alternatives: ["agar_agar", "halal_beef_gelatin", "pectin"], conversion_ratio: "1:0.5", category: "gelatin", status: "conditional", school_of_thought_variation: { hanafi: "haram", shafii: "haram", maliki: "haram", hanbali: "haram" }, inheritance: ["pork"], notes: "Agar is stronger than gelatin. Check the source before consuming. Must be halal-certified if animal-derived", quranic_reference: "Surah Al-Baqarah 2:173", hadith_reference: "Sahih Bukhari 7:67:400", confidence_score_base: 0.5, eli5: "Gelatin is made from animal parts, so whether it's halal depends on the animal." },
  marshmallows: { name: "marshmallows", aliases: ["marshmallow", "mallow_candy", "gelatin_candy"], halal_alternatives: ["halal_marshmallows", "vegan_marshmallows", "marshmallows_with_agar"], conversion_ratio: "1:1", category: "gelatin", status: "conditional", school_of_thought_variation: {}, inheritance: ["gelatin"], notes: "Marshmallows typically contain gelatin, which may come from pork sources. Must be halal-certified gelatin", quranic_reference: "Surah Al-Baqarah 2:173", hadith_reference: "Sahih Bukhari 7:67:400", confidence_score_base: 0.5, eli5: "Marshmallows often contain gelatin, which may come from pork." },
  gummy_candy: { name: "gummy_candy", aliases: ["gummies", "fruit_snacks", "jelly_candy", "chewy_candy", "gummy_bears"], halal_alternatives: ["halal_gummy_candy", "vegan_gummies", "fruit_leather"], conversion_ratio: "1:1", category: "gelatin", status: "conditional", school_of_thought_variation: {}, inheritance: ["gelatin"], notes: "Pork gelatin common. Must be halal-certified gelatin", quranic_reference: "Surah Al-Baqarah 2:173", hadith_reference: "Sahih Bukhari 7:67:400", confidence_score_base: 0.5, eli5: "Gummy candy often contains gelatin, which may come from pork." },
  jello: { name: "jello", aliases: ["jelly", "gelatin_dessert", "fruit_jelly"], halal_alternatives: ["agar_agar_jelly", "halal_jello", "fruit_gel"], conversion_ratio: "1:0.5", category: "gelatin", status: "conditional", school_of_thought_variation: {}, inheritance: ["gelatin"], notes: "Typically contains pork gelatin. Use agar-agar for halal version", quranic_reference: "Surah Al-Baqarah 2:173", hadith_reference: "Sahih Bukhari 7:67:400", confidence_score_base: 0.5, eli5: "Jello contains gelatin, which may come from pork." },
  lucky_charms: { name: "lucky_charms", aliases: ["lucky_charms_cereal"], halal_alternatives: ["halal_certified_cereals", "homemade_cereal", "cereal_without_marshmallows"], conversion_ratio: "1:1", category: "gelatin", status: "haram", school_of_thought_variation: {}, inheritance: ["marshmallows"], notes: "Lucky Charms contain marshmallows that typically use pork-derived gelatin", quranic_reference: "Surah Al-Baqarah 2:173", hadith_reference: "", confidence_score_base: 0.5, eli5: "Lucky Charms contain marshmallows that usually use pork gelatin." },
  marshmallow_fluff: { name: "marshmallow_fluff", aliases: ["marshmallow_creme"], halal_alternatives: ["halal_marshmallow_fluff"], conversion_ratio: "1:1", category: "gelatin", status: "conditional", school_of_thought_variation: {}, inheritance: ["gelatin"], notes: "Most contain pork gelatin", quranic_reference: "Surah Al-Baqarah 2:173", hadith_reference: "Sahih Muslim 10:3893", confidence_score_base: 0.5, eli5: "Marshmallow fluff usually contains gelatin, which may come from pork." },
  panna_cotta: { name: "panna_cotta", aliases: ["italian_cream_dessert"], halal_alternatives: ["panna_cotta_with_agar", "halal_panna_cotta"], conversion_ratio: "1:1", category: "gelatin", status: "conditional", school_of_thought_variation: {}, inheritance: ["gelatin"], notes: "Traditionally uses gelatin. Use agar-agar for halal version", quranic_reference: "Surah Al-Baqarah 2:173", hadith_reference: "Sahih Bukhari 7:67:400", confidence_score_base: 0.5, eli5: "Panna cotta contains gelatin, which may come from pork." },
  cheesecake: { name: "cheesecake", aliases: ["new_york_cheesecake", "baked_cheesecake"], halal_alternatives: ["halal_cheesecake", "no_bake_cheesecake_without_gelatin"], conversion_ratio: "1:1", category: "gelatin", status: "questionable", school_of_thought_variation: {}, inheritance: ["gelatin"], notes: "May contain gelatin in some recipes. Check ingredients or make halal version", quranic_reference: "Surah Al-Baqarah 2:173", hadith_reference: "Sahih Bukhari 7:67:400", confidence_score_base: 0.7, eli5: "Some cheesecakes contain gelatin, so check the ingredients." },
  yogurt_with_gelatin: { name: "yogurt_with_gelatin", aliases: ["gelatin_yogurt", "greek_yogurt_thickened"], halal_alternatives: ["yogurt_without_gelatin", "halal_certified_yogurt"], conversion_ratio: "1:1", category: "gelatin", status: "conditional", school_of_thought_variation: {}, inheritance: ["gelatin"], notes: "Check ingredients. Some yogurts use gelatin as thickener", quranic_reference: "Surah Al-Baqarah 2:173", hadith_reference: "Sahih Bukhari 7:67:400", confidence_score_base: 0.5, eli5: "Some yogurt contains gelatin to make it thicker, so check the ingredients." },
  ice_cream_gelatin: { name: "ice_cream_gelatin", aliases: ["gelatin_ice_cream"], halal_alternatives: ["gelato_without_gelatin", "halal_ice_cream"], conversion_ratio: "1:1", category: "gelatin", status: "conditional", school_of_thought_variation: {}, inheritance: ["gelatin"], notes: "May contain gelatin or alcohol", quranic_reference: "Surah Al-Baqarah 2:173", hadith_reference: "Sahih Muslim 10:3893", confidence_score_base: 0.5, eli5: "Some ice cream contains gelatin, so check the ingredients." },
  
  // ============ ALCOHOL & ALCOHOLIC INGREDIENTS (20+ entries) ============
  alcohol: { name: "alcohol", aliases: ["ethanol", "spirits", "liquor", "intoxicant"], halal_alternatives: ["non_alcoholic_substitutes", "vinegar", "broth"], conversion_ratio: "1:1", category: "alcohol", status: "haram", school_of_thought_variation: {}, inheritance: [], notes: "Alcohol in any form is prohibited in Islam", quranic_reference: "Surah Al-Ma'idah 5:90", hadith_reference: "Sahih Bukhari 7:69:494", confidence_score_base: 0.1, eli5: "Alcohol is forbidden in Islam." },
  wine: { name: "wine", aliases: ["red_wine", "white_wine", "cooking_wine", "wine_vinegar"], halal_alternatives: ["grape_juice_plus_vinegar", "non_alcoholic_wine"], conversion_ratio: "1:0.75", category: "alcohol", status: "haram", school_of_thought_variation: {}, inheritance: ["alcohol"], notes: "Use 3 parts juice + 1 part vinegar", quranic_reference: "Surah Al-Ma'idah 5:90", hadith_reference: "Sahih Bukhari 7:69:494", confidence_score_base: 0.1, eli5: "Wine contains alcohol, which is not allowed in Islam." },
  beer: { name: "beer", aliases: ["ale", "lager", "beer_batter", "stout"], halal_alternatives: ["malt_vinegar_plus_water", "sparkling_water", "non_alcoholic_beer"], conversion_ratio: "1:0.5", category: "alcohol", status: "haram", school_of_thought_variation: {}, inheritance: ["alcohol"], notes: "Reduces bitterness without alcohol", quranic_reference: "Surah Al-Ma'idah 5:90", hadith_reference: "Sahih Muslim 10:3893", confidence_score_base: 0.1, eli5: "Beer contains alcohol, which is forbidden in Islam." },
  rum: { name: "rum", aliases: ["dark_rum", "light_rum", "rum_extract", "rum_flavoring", "rum_essence"], halal_alternatives: ["vanilla_extract_plus_molasses", "alcohol_free_rum_flavor"], conversion_ratio: "1:0.75", category: "alcohol", status: "haram", school_of_thought_variation: {}, inheritance: ["alcohol"], notes: "Mimics depth without alcohol. Even small amounts are impermissible", quranic_reference: "Surah Al-Ma'idah 5:90", hadith_reference: "Sahih Muslim 10:3893", confidence_score_base: 0.1, eli5: "Rum contains alcohol, which is forbidden in Islam." },
  brandy: { name: "brandy", aliases: ["cognac", "brandy_flavor", "liqueur", "armagnac"], halal_alternatives: ["grape_juice_reduction", "alcohol_free_brandy_flavor"], conversion_ratio: "1:0.75", category: "alcohol", status: "haram", school_of_thought_variation: {}, inheritance: ["alcohol"], notes: "Reduces alcohol while keeping flavor", quranic_reference: "Surah Al-Ma'idah 5:90", hadith_reference: "Sahih Muslim 10:3883", confidence_score_base: 0.1, eli5: "Brandy contains alcohol, which is forbidden in Islam." },
  whiskey: { name: "whiskey", aliases: ["bourbon", "scotch", "whisky", "whiskey_sauce"], halal_alternatives: ["apple_juice_reduction", "alcohol_free_whiskey_flavor"], conversion_ratio: "1:0.75", category: "alcohol", status: "haram", school_of_thought_variation: {}, inheritance: ["alcohol"], notes: "Reduces bitterness and alcohol", quranic_reference: "Surah Al-Ma'idah 5:90", hadith_reference: "Sahih Bukhari 7:69:494", confidence_score_base: 0.1, eli5: "Whiskey contains alcohol, which is forbidden in Islam." },
  vodka: { name: "vodka", aliases: ["neutral_spirits", "vodka_sauce"], halal_alternatives: ["water_plus_citrus_extract", "non_alcoholic_vodka"], conversion_ratio: "1:1", category: "alcohol", status: "haram", school_of_thought_variation: {}, inheritance: ["alcohol"], notes: "Used only as solvent replacement", quranic_reference: "Surah Al-Ma'idah 5:90", hadith_reference: "Sahih Muslim 10:3883", confidence_score_base: 0.1, eli5: "Vodka contains alcohol, which is forbidden in Islam." },
  mirin: { name: "mirin", aliases: ["sweet_rice_wine", "cooking_sake", "japanese_rice_wine"], halal_alternatives: ["sugar_plus_rice_vinegar", "halal_mirin"], conversion_ratio: "1:0.5", category: "alcohol", status: "haram", school_of_thought_variation: {}, inheritance: ["alcohol"], notes: "1 tsp sugar + 1 tsp vinegar", quranic_reference: "Surah Al-Ma'idah 5:90", hadith_reference: "Sahih Muslim 10:3893", confidence_score_base: 0.1, eli5: "Mirin contains alcohol, which is forbidden in Islam." },
  sake: { name: "sake", aliases: ["rice_wine", "japanese_sake"], halal_alternatives: ["rice_vinegar", "non_alcoholic_sake"], conversion_ratio: "1:0.5", category: "alcohol", status: "haram", school_of_thought_variation: {}, inheritance: ["alcohol"], notes: "Rice wine contains alcohol", quranic_reference: "Surah Al-Ma'idah 5:90", hadith_reference: "Sahih Muslim 10:3893", confidence_score_base: 0.1, eli5: "Sake contains alcohol, which is forbidden in Islam." },
  vanilla_extract: { name: "vanilla_extract", aliases: ["vanilla_extract_alcohol", "pure_vanilla_extract", "imitation_vanilla"], halal_alternatives: ["alcohol_free_vanilla", "vanilla_powder", "vanilla_bean_paste"], conversion_ratio: "1:1", category: "flavoring", status: "questionable", school_of_thought_variation: { hanafi: "haram", shafii: "questionable", maliki: "questionable", hanbali: "haram" }, inheritance: ["alcohol"], notes: "Ensure alcohol-free labeling. Some scholars allow trace amounts, others don't", quranic_reference: "Surah Al-Ma'idah 5:90", hadith_reference: "Sahih Muslim 10:3893", confidence_score_base: 0.5, eli5: "Vanilla extract often has a little bit of alcohol in it, so check if it's alcohol-free." },
  almond_extract: { name: "almond_extract", aliases: ["almond_essence"], halal_alternatives: ["almond_flavoring_alcohol_free", "almond_paste"], conversion_ratio: "1:1", category: "flavoring", status: "questionable", school_of_thought_variation: { hanafi: "haram", shafii: "questionable", maliki: "questionable", hanbali: "haram" }, inheritance: ["alcohol"], notes: "Often contains alcohol as carrier. Check for alcohol-free version", quranic_reference: "Surah Al-Ma'idah 5:90", hadith_reference: "Sahih Muslim 10:3893", confidence_score_base: 0.5, eli5: "Almond extract might have alcohol, so check for alcohol-free versions." },
  lemon_extract: { name: "lemon_extract", aliases: ["lemon_essence"], halal_alternatives: ["lemon_zest", "lemon_juice", "alcohol_free_lemon_extract"], conversion_ratio: "1:1", category: "flavoring", status: "questionable", school_of_thought_variation: { hanafi: "haram", shafii: "questionable", maliki: "questionable", hanbali: "haram" }, inheritance: ["alcohol"], notes: "May contain alcohol. Use lemon zest or juice instead", quranic_reference: "Surah Al-Ma'idah 5:90", hadith_reference: "Sahih Muslim 10:3893", confidence_score_base: 0.5, eli5: "Lemon extract might have alcohol, so use lemon zest or juice instead." },
  
  // ============ MEAT & MEAT PRODUCTS (15+ entries) ============
  beef: { name: "beef", aliases: ["steak", "ground_beef", "beef_meat", "beef_roast"], halal_alternatives: ["halal_certified_beef"], conversion_ratio: "1:1", category: "meat", status: "questionable", school_of_thought_variation: {}, inheritance: [], notes: "Must be halal-certified (halal slaughter)", quranic_reference: "Surah Al-Baqarah 2:172", hadith_reference: "Sahih Bukhari 7:67:400", confidence_score_base: 1.0, eli5: "Beef is halal if the animal was prepared in the Islamic way." },
  chicken: { name: "chicken", aliases: ["chicken_meat", "poultry", "chicken_breast"], halal_alternatives: ["halal_certified_chicken"], conversion_ratio: "1:1", category: "meat", status: "questionable", school_of_thought_variation: {}, inheritance: [], notes: "Must be halal-certified (halal slaughter)", quranic_reference: "Surah Al-Baqarah 2:172", hadith_reference: "Sahih Bukhari 7:67:400", confidence_score_base: 1.0, eli5: "Chicken is halal if the animal was prepared in the Islamic way." },
  lamb: { name: "lamb", aliases: ["mutton", "lamb_meat", "lamb_chops"], halal_alternatives: ["halal_certified_lamb"], conversion_ratio: "1:1", category: "meat", status: "questionable", school_of_thought_variation: {}, inheritance: [], notes: "Must be halal-certified (halal slaughter)", quranic_reference: "Surah Al-Baqarah 2:172", hadith_reference: "Sahih Bukhari 7:67:400", confidence_score_base: 1.0, eli5: "Lamb is halal if the animal was prepared in the Islamic way." },
  turkey: { name: "turkey", aliases: ["turkey_meat", "turkey_breast"], halal_alternatives: ["halal_certified_turkey"], conversion_ratio: "1:1", category: "meat", status: "questionable", school_of_thought_variation: {}, inheritance: [], notes: "Must be halal-certified (halal slaughter)", quranic_reference: "Surah Al-Baqarah 2:172", hadith_reference: "Sahih Bukhari 7:67:400", confidence_score_base: 1.0, eli5: "Turkey is halal if the animal was prepared in the Islamic way." },
  ground_meat: { name: "ground_meat", aliases: ["minced_meat", "meat_mince"], halal_alternatives: ["halal_certified_ground_meat"], conversion_ratio: "1:1", category: "meat", status: "questionable", school_of_thought_variation: {}, inheritance: [], notes: "Must be halal-certified. Often contains mixed or non-halal meat", quranic_reference: "Surah Al-Baqarah 2:172", hadith_reference: "Sahih Bukhari 7:67:400", confidence_score_base: 0.8, eli5: "Ground meat must be from halal-certified animals." },
  meatballs: { name: "meatballs", aliases: ["frozen_meatballs", "italian_meatballs"], halal_alternatives: ["halal_beef_meatballs", "homemade_meatballs_halal"], conversion_ratio: "1:1", category: "meat", status: "haram", school_of_thought_variation: {}, inheritance: ["pork"], notes: "Frozen products often non-halal. Contains pork or non-halal beef", quranic_reference: "Surah Al-Baqarah 2:173", hadith_reference: "Sahih Bukhari 7:67:400", confidence_score_base: 0.1, eli5: "Store-bought meatballs often contain pork or non-halal meat." },
  
  // ============ CHEESE & DAIRY (10+ entries) ============
  rennet_cheese: { name: "rennet_cheese", aliases: ["animal_rennet_cheese", "traditional_cheese", "aged_cheese"], halal_alternatives: ["microbial_rennet_cheese", "vegetarian_cheese", "halal_certified_cheese"], conversion_ratio: "1:1", category: "additive", status: "haram", school_of_thought_variation: {}, inheritance: [], notes: "Most rennet comes from non-halal calves. Microbial rennet is halal-safe", quranic_reference: "Surah Al-Baqarah 2:173", hadith_reference: "Sahih Bukhari 7:67:400", confidence_score_base: 0.1, eli5: "Some cheese is made with enzymes from animals that weren't slaughtered halal." },
  animal_rennet: { name: "animal_rennet", aliases: ["rennet", "cheese_enzyme", "chymosin"], halal_alternatives: ["microbial_rennet", "vegetarian_rennet"], conversion_ratio: "1:1", category: "additive", status: "haram", school_of_thought_variation: {}, inheritance: [], notes: "Common in cheese production. Check for microbial/vegetarian sources", quranic_reference: "Surah Al-Baqarah 2:173", hadith_reference: "Sahih Bukhari 7:67:400", confidence_score_base: 0.1, eli5: "Animal rennet comes from the stomach of calves that may not be halal." },
  parmesan_cheese: { name: "parmesan_cheese", aliases: ["parmigiano_reggiano", "parmesan"], halal_alternatives: ["vegetarian_parmesan", "halal_certified_parmesan"], conversion_ratio: "1:1", category: "additive", status: "haram", school_of_thought_variation: {}, inheritance: ["animal_rennet"], notes: "Traditionally uses animal rennet. Look for vegetarian or halal-certified versions", quranic_reference: "Surah Al-Baqarah 2:173", hadith_reference: "Sahih Bukhari 7:67:400", confidence_score_base: 0.1, eli5: "Parmesan cheese often uses animal rennet, which may not be halal." },
  blue_cheese: { name: "blue_cheese", aliases: ["roquefort", "gorgonzola", "stilton"], halal_alternatives: ["halal_certified_blue_cheese", "vegetarian_blue_cheese"], conversion_ratio: "1:1", category: "additive", status: "haram", school_of_thought_variation: {}, inheritance: ["animal_rennet"], notes: "Often uses animal rennet. Check for halal-certified versions", quranic_reference: "Surah Al-Baqarah 2:173", hadith_reference: "Sahih Bukhari 7:67:400", confidence_score_base: 0.1, eli5: "Blue cheese often uses animal rennet, which may not be halal." },
  feta_cheese: { name: "feta_cheese", aliases: ["feta"], halal_alternatives: ["halal_certified_feta", "vegetarian_feta"], conversion_ratio: "1:1", category: "additive", status: "questionable", school_of_thought_variation: {}, inheritance: ["animal_rennet"], notes: "May use animal rennet. Check ingredients or use halal-certified", quranic_reference: "Surah Al-Baqarah 2:173", hadith_reference: "Sahih Bukhari 7:67:400", confidence_score_base: 0.5, eli5: "Feta cheese might use animal rennet, so check the ingredients." },
  
  // ============ ADDITIVES & EMULSIFIERS (20+ entries) ============
  mono_diglycerides: { name: "mono_diglycerides", aliases: ["e471", "emulsifier", "glycerides"], halal_alternatives: ["plant_based_emulsifier", "lecithin"], conversion_ratio: "1:1", category: "additive", status: "questionable", school_of_thought_variation: {}, inheritance: [], notes: "Source-dependent ingredient. May be animal-derived unless specified plant-based", quranic_reference: "Surah Al-Baqarah 2:172", hadith_reference: "Sahih Muslim 10:3893", confidence_score_base: 0.5, eli5: "This ingredient can come from animal or plant sources, so check the label." },
  l_cysteine: { name: "l_cysteine", aliases: ["e920", "dough_conditioner", "cysteine"], halal_alternatives: ["plant_based_l_cysteine", "synthetic_l_cysteine"], conversion_ratio: "1:1", category: "additive", status: "haram", school_of_thought_variation: {}, inheritance: [], notes: "Often derived from human hair or feathers. Must be plant-based or synthetic", quranic_reference: "Surah Al-Baqarah 2:173", hadith_reference: "Sahih Muslim 10:3893", confidence_score_base: 0.1, eli5: "This ingredient often comes from human hair, which is not halal." },
  carmine: { name: "carmine", aliases: ["e120", "cochineal", "carmine_red", "natural_red_4"], halal_alternatives: ["beetroot_color", "paprika_extract", "red_cabbage_extract"], conversion_ratio: "1:1", category: "additive", status: "questionable", school_of_thought_variation: { hanafi: "haram", shafii: "questionable", maliki: "questionable", hanbali: "haram" }, inheritance: [], notes: "Derived from insects (cochineal). Some schools allow, others don't", quranic_reference: "Surah Al-Baqarah 2:173", hadith_reference: "Sahih Bukhari 7:67:400", confidence_score_base: 0.5, eli5: "This red color comes from insects, which some Muslims avoid." },
  shellac: { name: "shellac", aliases: ["e904", "confectioners_glaze", "food_glaze", "lac_resin"], halal_alternatives: ["plant_based_glaze", "carnauba_wax"], conversion_ratio: "1:1", category: "additive", status: "questionable", school_of_thought_variation: { hanafi: "haram", shafii: "questionable", maliki: "questionable", hanbali: "haram" }, inheritance: [], notes: "Derived from insects. Used as shiny coating on candies", quranic_reference: "Surah Al-Baqarah 2:173", hadith_reference: "Sahih Bukhari 7:67:400", confidence_score_base: 0.5, eli5: "This shiny coating comes from insects, which some Muslims avoid." },
  pepsin: { name: "pepsin", aliases: ["digestive_enzyme", "pepsin_enzyme"], halal_alternatives: ["plant_based_enzymes", "microbial_enzymes"], conversion_ratio: "1:1", category: "additive", status: "haram", school_of_thought_variation: {}, inheritance: [], notes: "Derived from pig stomach lining. Must use plant-based alternatives", quranic_reference: "Surah Al-Baqarah 2:173", hadith_reference: "Sahih Bukhari 7:67:400", confidence_score_base: 0.1, eli5: "Pepsin comes from pig stomachs, which is forbidden." },
  animal_shortening: { name: "animal_shortening", aliases: ["shortening", "tallow_shortening", "animal_fat_shortening"], halal_alternatives: ["vegetable_shortening", "halal_certified_shortening"], conversion_ratio: "1:1", category: "fat", status: "questionable", school_of_thought_variation: {}, inheritance: [], notes: "May contain pork fat. Check label for animal fats", quranic_reference: "Surah Al-Baqarah 2:173", hadith_reference: "Sahih Bukhari 7:67:400", confidence_score_base: 0.5, eli5: "This shortening might contain pork fat, so check the label." },
  glycerin: { name: "glycerin", aliases: ["glycerol", "e422"], halal_alternatives: ["vegetable_glycerin", "plant_based_glycerin"], conversion_ratio: "1:1", category: "additive", status: "questionable", school_of_thought_variation: {}, inheritance: [], notes: "Animal origin possible. Must be vegetable glycerin", quranic_reference: "Surah Al-Baqarah 2:173", hadith_reference: "Sahih Muslim 13:3808", confidence_score_base: 0.5, eli5: "Glycerin can come from animals or plants, so check for vegetable glycerin." },
  lecithin_animal: { name: "lecithin_animal", aliases: ["e322_animal", "animal_lecithin"], halal_alternatives: ["soy_lecithin", "sunflower_lecithin"], conversion_ratio: "1:1", category: "additive", status: "questionable", school_of_thought_variation: {}, inheritance: [], notes: "Animal lecithin uncommon but possible. Soy or sunflower preferred", quranic_reference: "Surah Al-Baqarah 2:173", hadith_reference: "Sahih Muslim 13:3808", confidence_score_base: 0.5, eli5: "Lecithin can come from animals, so look for soy or sunflower lecithin." },
  lipase: { name: "lipase", aliases: ["lipase_enzyme", "animal_lipase"], halal_alternatives: ["microbial_lipase", "plant_based_lipase"], conversion_ratio: "1:1", category: "additive", status: "haram", school_of_thought_variation: {}, inheritance: [], notes: "Often pork-derived unless specified. Used in cheese flavoring", quranic_reference: "Surah Al-Baqarah 2:173", hadith_reference: "Sahih Muslim 13:3808", confidence_score_base: 0.1, eli5: "Lipase often comes from pork, which is forbidden." },
  natural_flavors_meat: { name: "natural_flavors_meat", aliases: ["natural_flavoring", "meat_flavoring"], halal_alternatives: ["plant_based_flavor_extracts", "halal_certified_flavors"], conversion_ratio: "1:1", category: "flavoring", status: "questionable", school_of_thought_variation: {}, inheritance: [], notes: "Can contain meat or alcohol carriers. Check for halal-certified or plant-based", quranic_reference: "Surah Al-Baqarah 2:173", hadith_reference: "Sahih Muslim 13:3808", confidence_score_base: 0.5, eli5: "Natural flavors might contain meat or alcohol, so check for halal versions." },
  whey_protein: { name: "whey_protein", aliases: ["whey", "milk_whey"], halal_alternatives: ["halal_certified_whey", "plant_based_protein"], conversion_ratio: "1:1", category: "additive", status: "questionable", school_of_thought_variation: {}, inheritance: [], notes: "May be from non-halal dairy. Check for halal-certified", quranic_reference: "Surah Al-Baqarah 2:172", hadith_reference: "Sahih Bukhari 7:67:400", confidence_score_base: 0.7, eli5: "Whey protein might come from non-halal dairy, so check for halal-certified." },
  casein: { name: "casein", aliases: ["milk_casein", "casein_protein"], halal_alternatives: ["halal_certified_casein", "plant_based_protein"], conversion_ratio: "1:1", category: "additive", status: "questionable", school_of_thought_variation: {}, inheritance: [], notes: "Milk protein. Check for halal-certified dairy source", quranic_reference: "Surah Al-Baqarah 2:172", hadith_reference: "Sahih Bukhari 7:67:400", confidence_score_base: 0.7, eli5: "Casein is a milk protein, so make sure it's from halal dairy." },
  
  // ============ SAUCES & CONDIMENTS (15+ entries) ============
  worcestershire_sauce: { name: "worcestershire_sauce", aliases: ["worcestershire", "anchovy_sauce"], halal_alternatives: ["halal_worcestershire", "soy_sauce_with_vinegar"], conversion_ratio: "1:1", category: "flavoring", status: "questionable", school_of_thought_variation: {}, inheritance: ["alcohol"], notes: "Often fermented with alcohol. Check for halal-certified version", quranic_reference: "Surah Al-Ma'idah 5:90", hadith_reference: "Sahih Muslim 10:3893", confidence_score_base: 0.5, eli5: "This sauce might contain alcohol, so check for halal versions." },
  teriyaki_sauce: { name: "teriyaki_sauce", aliases: ["teriyaki_glaze", "teriyaki_marinade"], halal_alternatives: ["halal_teriyaki_sauce", "homemade_teriyaki"], conversion_ratio: "1:1", category: "flavoring", status: "haram", school_of_thought_variation: {}, inheritance: ["alcohol"], notes: "Often contains mirin or sake (alcohol). Make homemade halal version", quranic_reference: "Surah Al-Ma'idah 5:90", hadith_reference: "Sahih Bukhari 7:69:494", confidence_score_base: 0.1, eli5: "Teriyaki sauce often contains alcohol from mirin or sake." },
  oyster_sauce: { name: "oyster_sauce", aliases: ["oyster_sauce", "stir_fry_sauce"], halal_alternatives: ["alcohol_free_oyster_sauce", "mushroom_sauce"], conversion_ratio: "1:1", category: "flavoring", status: "questionable", school_of_thought_variation: { hanafi: "haram", shafii: "questionable", maliki: "questionable", hanbali: "questionable" }, inheritance: [], notes: "Some brands contain alcohol. Hanafi school: haram due to shellfish. Others: check for alcohol", quranic_reference: "Surah Al-Ma'idah 5:90", hadith_reference: "Sahih Muslim 10:3893", confidence_score_base: 0.5, eli5: "This sauce contains oysters and might have alcohol, so check for halal versions." },
  soy_sauce: { name: "soy_sauce", aliases: ["shoyu", "soy_sauce_fermented"], halal_alternatives: ["halal_certified_soy_sauce", "tamari_alcohol_free"], conversion_ratio: "1:1", category: "flavoring", status: "questionable", school_of_thought_variation: {}, inheritance: ["alcohol"], notes: "Naturally produces alcohol during fermentation. Most scholars allow if trace amounts", quranic_reference: "Surah Al-Ma'idah 5:90", hadith_reference: "Sahih Muslim 10:3893", confidence_score_base: 0.8, eli5: "Soy sauce naturally has tiny amounts of alcohol from fermentation, but most scholars allow it." },
  hoisin_sauce: { name: "hoisin_sauce", aliases: ["hoisin_glaze"], halal_alternatives: ["halal_hoisin_sauce", "homemade_hoisin"], conversion_ratio: "1:1", category: "flavoring", status: "questionable", school_of_thought_variation: {}, inheritance: ["alcohol"], notes: "Some brands contain alcohol", quranic_reference: "Surah Al-Ma'idah 5:90", hadith_reference: "Sahih Muslim 10:3893", confidence_score_base: 0.5, eli5: "Hoisin sauce might contain alcohol, so check the ingredients." },
  bbq_sauce: { name: "bbq_sauce", aliases: ["barbecue_sauce", "smoky_sauce"], halal_alternatives: ["alcohol_free_bbq_sauce", "homemade_bbq"], conversion_ratio: "1:1", category: "flavoring", status: "questionable", school_of_thought_variation: {}, inheritance: ["alcohol"], notes: "Some brands add whiskey or wine", quranic_reference: "Surah Al-Ma'idah 5:90", hadith_reference: "Sahih Muslim 10:3893", confidence_score_base: 0.5, eli5: "BBQ sauce might contain alcohol, so check the ingredients." },
  demi_glace: { name: "demi_glace", aliases: ["brown_sauce", "meat_glaze"], halal_alternatives: ["halal_demi_glace", "beef_stock_reduction"], conversion_ratio: "1:1", category: "flavoring", status: "haram", school_of_thought_variation: {}, inheritance: ["alcohol"], notes: "Traditionally made with wine", quranic_reference: "Surah Al-Ma'idah 5:90", hadith_reference: "Sahih Bukhari 7:69:494", confidence_score_base: 0.1, eli5: "Demi-glace is usually made with wine, which contains alcohol." },
  
  // ============ PROCESSED FOODS (15+ entries) ============
  ramen_seasoning: { name: "ramen_seasoning", aliases: ["instant_noodle_seasoning", "ramen_flavor_packet"], halal_alternatives: ["halal_seasoning_mix", "homemade_ramen_seasoning"], conversion_ratio: "1:1", category: "flavoring", status: "haram", school_of_thought_variation: {}, inheritance: ["pork"], notes: "Often contains pork extract or pork-based flavoring", quranic_reference: "Surah Al-Baqarah 2:173", hadith_reference: "Sahih Bukhari 7:67:400", confidence_score_base: 0.1, eli5: "Ramen seasoning often contains pork flavoring, which is forbidden." },
  frozen_lasagna: { name: "frozen_lasagna", aliases: ["ready_made_lasagna", "prepared_lasagna"], halal_alternatives: ["halal_lasagna", "homemade_lasagna"], conversion_ratio: "1:1", category: "processed_food", status: "haram", school_of_thought_variation: {}, inheritance: ["pork"], notes: "Contains pork or non-halal beef. Check ingredients carefully", quranic_reference: "Surah Al-Baqarah 2:173", hadith_reference: "Sahih Muslim 13:3808", confidence_score_base: 0.1, eli5: "Frozen lasagna often contains pork or meat that isn't halal." },
  refried_beans: { name: "refried_beans", aliases: ["refried_beans_lard"], halal_alternatives: ["vegetable_oil_refried_beans", "homemade_refried_beans"], conversion_ratio: "1:1", category: "processed_food", status: "questionable", school_of_thought_variation: {}, inheritance: ["pork"], notes: "Lard frequently used. Must check label for vegetable oil version", quranic_reference: "Surah Al-Baqarah 2:173", hadith_reference: "Sahih Muslim 13:3808", confidence_score_base: 0.5, eli5: "Refried beans are often cooked with pork fat, so check the label." },
  canned_soup: { name: "canned_soup", aliases: ["ready_soup", "prepared_soup"], halal_alternatives: ["halal_certified_soup", "homemade_soup"], conversion_ratio: "1:1", category: "processed_food", status: "questionable", school_of_thought_variation: {}, inheritance: [], notes: "Hidden animal fats common. Check ingredients", quranic_reference: "Surah Al-Baqarah 2:173", hadith_reference: "Sahih Bukhari 7:67:400", confidence_score_base: 0.5, eli5: "Canned soup might contain pork fat or non-halal meat, so check the ingredients." },
  gravy_mix: { name: "gravy_mix", aliases: ["instant_gravy", "gravy_powder"], halal_alternatives: ["halal_gravy", "mushroom_gravy"], conversion_ratio: "1:1", category: "processed_food", status: "haram", school_of_thought_variation: {}, inheritance: ["pork"], notes: "Often contains meat extract or pork flavoring", quranic_reference: "Surah Al-Baqarah 2:173", hadith_reference: "Sahih Bukhari 7:67:400", confidence_score_base: 0.1, eli5: "Gravy mix often contains pork or non-halal meat extracts." },
  stuffing_mix: { name: "stuffing_mix", aliases: ["stuffing", "dressing_mix"], halal_alternatives: ["halal_stuffing", "homemade_stuffing"], conversion_ratio: "1:1", category: "processed_food", status: "questionable", school_of_thought_variation: {}, inheritance: [], notes: "May contain animal fat", quranic_reference: "Surah Al-Baqarah 2:173", hadith_reference: "Sahih Muslim 10:3893", confidence_score_base: 0.5, eli5: "Stuffing mix might contain pork fat, so check the ingredients." },
  potato_chips_lard: { name: "potato_chips_lard", aliases: ["fried_chips", "lard_fried_chips"], halal_alternatives: ["vegetable_oil_chips", "halal_certified_chips"], conversion_ratio: "1:1", category: "processed_food", status: "questionable", school_of_thought_variation: {}, inheritance: ["pork"], notes: "Some brands fry in pork fat", quranic_reference: "Surah Al-Baqarah 2:173", hadith_reference: "Sahih Bukhari 7:67:400", confidence_score_base: 0.5, eli5: "Some potato chips are fried in pork fat, so check the label." },
  donuts: { name: "donuts", aliases: ["donuts_nonhalal", "fried_dough"], halal_alternatives: ["halal_donuts", "homemade_donuts"], conversion_ratio: "1:1", category: "processed_food", status: "questionable", school_of_thought_variation: {}, inheritance: [], notes: "Fried in animal fat sometimes", quranic_reference: "Surah Al-Baqarah 2:173", hadith_reference: "Sahih Bukhari 7:67:400", confidence_score_base: 0.5, eli5: "Donuts might be fried in pork fat, so check where they're from." },
  pastries_with_lard: { name: "pastries_with_lard", aliases: ["lard_pastry", "shortening_pastry"], halal_alternatives: ["butter_pastry", "vegetable_shortening_pastry"], conversion_ratio: "1:1", category: "processed_food", status: "haram", school_of_thought_variation: {}, inheritance: ["pork"], notes: "Lard commonly used in bakeries", quranic_reference: "Surah Al-Baqarah 2:173", hadith_reference: "Sahih Muslim 10:3893", confidence_score_base: 0.1, eli5: "Pastries often contain pork fat (lard), which is forbidden." },
  
  // ============ DESSERTS & SWEETS (15+ entries) ============
  custard: { name: "custard", aliases: ["cream_filling", "custard_powder"], halal_alternatives: ["halal_custard", "homemade_custard"], conversion_ratio: "1:1", category: "dessert", status: "questionable", school_of_thought_variation: {}, inheritance: ["vanilla_extract"], notes: "Check vanilla source (may contain alcohol)", quranic_reference: "Surah Al-Baqarah 2:172", hadith_reference: "Sahih Muslim 10:3893", confidence_score_base: 0.7, eli5: "Custard might contain vanilla extract with alcohol, so check the ingredients." },
  cake_glaze: { name: "cake_glaze", aliases: ["mirror_glaze", "sugar_glaze"], halal_alternatives: ["fruit_glaze", "sugar_glaze", "chocolate_glaze"], conversion_ratio: "1:1", category: "dessert", status: "questionable", school_of_thought_variation: {}, inheritance: ["alcohol"], notes: "Some glazes use alcohol. Use fruit or sugar glazes instead", quranic_reference: "Surah Al-Ma'idah 5:90", hadith_reference: "Sahih Muslim 10:3893", confidence_score_base: 0.5, eli5: "Some cake glazes use alcohol, so check the ingredients." },
  liqueur_chocolate: { name: "liqueur_chocolate", aliases: ["alcohol_chocolate", "chocolate_with_liqueur"], halal_alternatives: ["halal_chocolate_filling", "chocolate_without_alcohol"], conversion_ratio: "1:1", category: "dessert", status: "haram", school_of_thought_variation: {}, inheritance: ["alcohol"], notes: "Contains intoxicants. Avoid all chocolate with alcohol fillings", quranic_reference: "Surah Al-Ma'idah 5:90", hadith_reference: "Sahih Muslim 10:3893", confidence_score_base: 0.1, eli5: "This chocolate contains alcohol, which is forbidden." },
  tiramisu: { name: "tiramisu", aliases: ["italian_dessert"], halal_alternatives: ["halal_tiramisu", "non_alcoholic_tiramisu"], conversion_ratio: "1:1", category: "dessert", status: "haram", school_of_thought_variation: {}, inheritance: ["alcohol"], notes: "Contains coffee liqueur or alcohol. Make halal version without alcohol", quranic_reference: "Surah Al-Ma'idah 5:90", hadith_reference: "Sahih Muslim 10:3893", confidence_score_base: 0.1, eli5: "Tiramisu contains alcohol, which is forbidden." },
  rum_cake: { name: "rum_cake", aliases: ["liqueur_cake", "alcohol_cake"], halal_alternatives: ["alcohol_free_cake", "vanilla_cake"], conversion_ratio: "1:1", category: "dessert", status: "haram", school_of_thought_variation: {}, inheritance: ["alcohol"], notes: "Alcohol used for moisture/flavor", quranic_reference: "Surah Al-Ma'idah 5:90", hadith_reference: "Sahih Bukhari 7:69:494", confidence_score_base: 0.1, eli5: "Rum cake contains alcohol, which is forbidden." },
  chocolate_liqueurs: { name: "chocolate_liqueurs", aliases: ["chocolate_liqueur_filling"], halal_alternatives: ["chocolate_without_liqueur", "chocolate_ganache"], conversion_ratio: "1:1", category: "dessert", status: "haram", school_of_thought_variation: {}, inheritance: ["alcohol"], notes: "Contains alcohol fillings. Avoid all varieties", quranic_reference: "Surah Al-Ma'idah 5:90", hadith_reference: "Sahih Muslim 10:3893", confidence_score_base: 0.1, eli5: "These chocolates contain alcohol, which is forbidden." },
  
  // ============ BROTH & STOCK (5+ entries) ============
  chicken_broth: { name: "chicken_broth", aliases: ["chicken_stock", "broth_nonhalal"], halal_alternatives: ["halal_chicken_broth", "vegetable_broth"], conversion_ratio: "1:1", category: "meat", status: "questionable", school_of_thought_variation: {}, inheritance: [], notes: "Must be halal-slaughtered", quranic_reference: "Surah Al-Baqarah 2:173", hadith_reference: "Sahih Bukhari 7:67:400", confidence_score_base: 0.7, eli5: "Chicken broth must be from halal-certified chickens." },
  beef_broth: { name: "beef_broth", aliases: ["beef_stock", "broth_nonhalal"], halal_alternatives: ["halal_beef_broth", "vegetable_broth"], conversion_ratio: "1:1", category: "meat", status: "questionable", school_of_thought_variation: {}, inheritance: [], notes: "Common in soups and rice. Must be halal-certified", quranic_reference: "Surah Al-Baqarah 2:173", hadith_reference: "Sahih Muslim 13:3808", confidence_score_base: 0.7, eli5: "Beef broth must be from halal-certified beef." },
  meat_extract: { name: "meat_extract", aliases: ["meat_extract", "beef_extract"], halal_alternatives: ["halal_yeast_extract", "vegetable_broth_concentrate"], conversion_ratio: "1:1", category: "flavoring", status: "haram", school_of_thought_variation: {}, inheritance: ["pork"], notes: "Yeast provides similar depth. Often contains non-halal meat", quranic_reference: "Surah Al-Baqarah 2:173", hadith_reference: "Sahih Muslim 10:3893", confidence_score_base: 0.1, eli5: "Meat extract often contains pork or non-halal meat." },
  
  // ============ ADDITIONAL PROCESSED INGREDIENTS ============
  cooking_spray: { name: "cooking_spray", aliases: ["pan_spray", "release_spray"], halal_alternatives: ["plant_based_cooking_spray", "vegetable_oil_spray"], conversion_ratio: "1:1", category: "additive", status: "questionable", school_of_thought_variation: {}, inheritance: [], notes: "May contain animal-derived lecithin", quranic_reference: "Surah Al-Baqarah 2:173", hadith_reference: "Sahih Bukhari 7:67:400", confidence_score_base: 0.5, eli5: "Cooking spray might contain animal-based ingredients, so check the label." },
  mustard_wine: { name: "mustard_wine", aliases: ["dijon_mustard"], halal_alternatives: ["mustard_with_halal_vinegar", "yellow_mustard"], conversion_ratio: "1:1", category: "flavoring", status: "questionable", school_of_thought_variation: {}, inheritance: ["alcohol"], notes: "Some use wine vinegar", quranic_reference: "Surah Al-Ma'idah 5:90", hadith_reference: "Sahih Muslim 10:3893", confidence_score_base: 0.5, eli5: "Some mustard uses wine vinegar, so check the ingredients." },
  wine_vinegar: { name: "wine_vinegar", aliases: ["red_wine_vinegar", "white_wine_vinegar"], halal_alternatives: ["apple_cider_vinegar", "rice_vinegar"], conversion_ratio: "1:1", category: "alcohol", status: "questionable", school_of_thought_variation: {}, inheritance: ["alcohol"], notes: "No alcohol involvement in final product. Some scholars allow", quranic_reference: "Surah Al-Ma'idah 5:90", hadith_reference: "Sahih Muslim 10:3883", confidence_score_base: 0.7, eli5: "Wine vinegar is usually okay because the alcohol is gone, but some Muslims avoid it." },
  balsamic_vinegar: { name: "balsamic_vinegar", aliases: ["balsamic"], halal_alternatives: ["halal_balsamic", "aged_balsamic_without_wine"], conversion_ratio: "1:1", category: "flavoring", status: "questionable", school_of_thought_variation: {}, inheritance: [], notes: "Traditional balsamic is grape-based only, no alcohol. Check ingredients", quranic_reference: "Surah Al-Baqarah 2:172", hadith_reference: "Sahih Bukhari 7:67:400", confidence_score_base: 0.8, eli5: "Real balsamic vinegar doesn't have alcohol, but check the ingredients to be sure." },
  
  // ============ ADDITIONAL PORK PRODUCTS ============
  pancetta: { name: "pancetta", aliases: ["italian_bacon", "cured_pork_belly"], halal_alternatives: ["beef_pancetta_halal", "turkey_pancetta"], conversion_ratio: "1:1", category: "meat", status: "haram", school_of_thought_variation: {}, inheritance: ["pork"], notes: "Italian cured pork belly. Use halal beef or turkey version", quranic_reference: "Surah Al-Baqarah 2:173", hadith_reference: "Sahih Bukhari 7:67:400", confidence_score_base: 0.1, eli5: "Pancetta is made from pork, which is forbidden." },
  prosciutto: { name: "prosciutto", aliases: ["italian_ham", "dry_cured_ham"], halal_alternatives: ["beef_prosciutto_halal", "turkey_prosciutto"], conversion_ratio: "1:1", category: "meat", status: "haram", school_of_thought_variation: {}, inheritance: ["pork"], notes: "Italian dry-cured ham. Must use halal-certified alternatives", quranic_reference: "Surah Al-Baqarah 2:173", hadith_reference: "Sahih Bukhari 7:67:400", confidence_score_base: 0.1, eli5: "Prosciutto is made from pork, which is forbidden." },
  pork_belly: { name: "pork_belly", aliases: ["pork_fat"], halal_alternatives: ["chicken_thigh", "beef_brisket_halal"], conversion_ratio: "1:1", category: "meat", status: "haram", school_of_thought_variation: {}, inheritance: ["pork"], notes: "High fat content. Chicken thigh works well", quranic_reference: "Surah Al-Baqarah 2:173", hadith_reference: "Sahih Bukhari 7:67:400", confidence_score_base: 0.1, eli5: "Pork belly is from pigs, which are forbidden." },
  chorizo: { name: "chorizo", aliases: ["spanish_sausage", "mexican_chorizo"], halal_alternatives: ["beef_chorizo_halal", "chicken_chorizo"], conversion_ratio: "1:1", category: "meat", status: "haram", school_of_thought_variation: {}, inheritance: ["pork"], notes: "Spicy sausage typically pork-based. Use halal beef or chicken version", quranic_reference: "Surah Al-Baqarah 2:173", hadith_reference: "Sahih Muslim 10:3893", confidence_score_base: 0.1, eli5: "Chorizo is usually made from pork, which is forbidden." },
  
  // ============ ADDITIONAL GELATIN PRODUCTS ============
  jelly_candies: { name: "jelly_candies", aliases: ["jelly_beans", "fruit_jellies"], halal_alternatives: ["halal_jelly_candies", "vegan_jelly_candies"], conversion_ratio: "1:1", category: "gelatin", status: "conditional", school_of_thought_variation: {}, inheritance: ["gelatin"], notes: "Pork gelatin common. Must be halal-certified", quranic_reference: "Surah Al-Baqarah 2:173", hadith_reference: "Sahih Bukhari 7:67:400", confidence_score_base: 0.5, eli5: "Jelly candies often contain gelatin, which may come from pork." },
  fruit_snacks: { name: "fruit_snacks", aliases: ["fruit_rolls", "fruit_gushers"], halal_alternatives: ["halal_fruit_snacks", "fruit_leather"], conversion_ratio: "1:1", category: "gelatin", status: "conditional", school_of_thought_variation: {}, inheritance: ["gelatin"], notes: "Often contains gelatin for texture", quranic_reference: "Surah Al-Baqarah 2:173", hadith_reference: "Sahih Bukhari 7:67:400", confidence_score_base: 0.5, eli5: "Fruit snacks might contain gelatin, so check the ingredients." },
  mousse: { name: "mousse", aliases: ["chocolate_mousse", "dessert_mousse"], halal_alternatives: ["mousse_without_gelatin", "vegan_mousse"], conversion_ratio: "1:1", category: "gelatin", status: "questionable", school_of_thought_variation: {}, inheritance: ["gelatin"], notes: "Some recipes use gelatin. Check ingredients or make without gelatin", quranic_reference: "Surah Al-Baqarah 2:173", hadith_reference: "Sahih Bukhari 7:67:400", confidence_score_base: 0.7, eli5: "Some mousse desserts contain gelatin, so check the ingredients." },
  pate_de_fruit: { name: "pate_de_fruit", aliases: ["fruit_paste", "fruit_confit"], halal_alternatives: ["pate_de_fruit_with_agar", "halal_fruit_confit"], conversion_ratio: "1:1", category: "gelatin", status: "conditional", school_of_thought_variation: {}, inheritance: ["gelatin"], notes: "Traditionally uses pectin or gelatin. Use agar-agar for halal version", quranic_reference: "Surah Al-Baqarah 2:173", hadith_reference: "Sahih Bukhari 7:67:400", confidence_score_base: 0.5, eli5: "Fruit paste might contain gelatin, so check the ingredients." },
  
  // ============ ADDITIONAL ALCOHOL VARIATIONS ============
  grand_marnier: { name: "grand_marnier", aliases: ["orange_liqueur", "curacao"], halal_alternatives: ["orange_extract", "orange_juice_reduction"], conversion_ratio: "1:0.75", category: "alcohol", status: "haram", school_of_thought_variation: {}, inheritance: ["alcohol"], notes: "Orange-flavored liqueur. Use orange extract instead", quranic_reference: "Surah Al-Ma'idah 5:90", hadith_reference: "Sahih Muslim 10:3893", confidence_score_base: 0.1, eli5: "Grand Marnier contains alcohol, which is forbidden." },
  kirsch: { name: "kirsch", aliases: ["cherry_liqueur", "cherry_brandy"], halal_alternatives: ["cherry_extract", "cherry_juice"], conversion_ratio: "1:1", category: "alcohol", status: "haram", school_of_thought_variation: {}, inheritance: ["alcohol"], notes: "Cherry-flavored alcohol. Use cherry extract or juice", quranic_reference: "Surah Al-Ma'idah 5:90", hadith_reference: "Sahih Muslim 10:3893", confidence_score_base: 0.1, eli5: "Kirsch contains alcohol, which is forbidden." },
  amaretto: { name: "amaretto", aliases: ["almond_liqueur"], halal_alternatives: ["almond_extract", "amaretto_flavoring_alcohol_free"], conversion_ratio: "1:1", category: "alcohol", status: "haram", school_of_thought_variation: {}, inheritance: ["alcohol"], notes: "Almond-flavored liqueur. Use almond extract instead", quranic_reference: "Surah Al-Ma'idah 5:90", hadith_reference: "Sahih Muslim 10:3893", confidence_score_base: 0.1, eli5: "Amaretto contains alcohol, which is forbidden." },
  kahlua: { name: "kahlua", aliases: ["coffee_liqueur"], halal_alternatives: ["coffee_extract", "espresso_plus_sugar"], conversion_ratio: "1:1", category: "alcohol", status: "haram", school_of_thought_variation: {}, inheritance: ["alcohol"], notes: "Coffee-flavored liqueur. Use strong espresso instead", quranic_reference: "Surah Al-Ma'idah 5:90", hadith_reference: "Sahih Muslim 10:3893", confidence_score_base: 0.1, eli5: "Kahlua contains alcohol, which is forbidden." },
  
  // ============ ADDITIONAL CHEESE VARIETIES ============
  brie_cheese: { name: "brie_cheese", aliases: ["brie", "soft_cheese"], halal_alternatives: ["halal_certified_brie", "vegetarian_brie"], conversion_ratio: "1:1", category: "additive", status: "questionable", school_of_thought_variation: {}, inheritance: ["animal_rennet"], notes: "May use animal rennet. Check for vegetarian or halal-certified", quranic_reference: "Surah Al-Baqarah 2:173", hadith_reference: "Sahih Bukhari 7:67:400", confidence_score_base: 0.5, eli5: "Brie cheese might use animal rennet, so check the ingredients." },
  camembert: { name: "camembert", aliases: ["french_soft_cheese"], halal_alternatives: ["halal_certified_camembert", "vegetarian_camembert"], conversion_ratio: "1:1", category: "additive", status: "questionable", school_of_thought_variation: {}, inheritance: ["animal_rennet"], notes: "Soft cheese may use animal rennet. Check label", quranic_reference: "Surah Al-Baqarah 2:173", hadith_reference: "Sahih Bukhari 7:67:400", confidence_score_base: 0.5, eli5: "Camembert might use animal rennet, so check the ingredients." },
  gouda: { name: "gouda", aliases: ["dutch_cheese"], halal_alternatives: ["halal_certified_gouda", "vegetarian_gouda"], conversion_ratio: "1:1", category: "additive", status: "questionable", school_of_thought_variation: {}, inheritance: ["animal_rennet"], notes: "Often uses animal rennet. Look for vegetarian or halal versions", quranic_reference: "Surah Al-Baqarah 2:173", hadith_reference: "Sahih Bukhari 7:67:400", confidence_score_base: 0.5, eli5: "Gouda might use animal rennet, so check the ingredients." },
  cheddar: { name: "cheddar", aliases: ["cheddar_cheese", "aged_cheddar"], halal_alternatives: ["halal_certified_cheddar", "vegetarian_cheddar"], conversion_ratio: "1:1", category: "additive", status: "questionable", school_of_thought_variation: {}, inheritance: ["animal_rennet"], notes: "May use animal rennet. Check for vegetarian or halal versions", quranic_reference: "Surah Al-Baqarah 2:173", hadith_reference: "Sahih Bukhari 7:67:400", confidence_score_base: 0.5, eli5: "Cheddar cheese might use animal rennet, so check the ingredients." },
  swiss_cheese: { name: "swiss_cheese", aliases: ["emmental", "gruyere"], halal_alternatives: ["halal_certified_swiss", "vegetarian_swiss"], conversion_ratio: "1:1", category: "additive", status: "questionable", school_of_thought_variation: {}, inheritance: ["animal_rennet"], notes: "Often uses animal rennet. Check for halal-certified versions", quranic_reference: "Surah Al-Baqarah 2:173", hadith_reference: "Sahih Bukhari 7:67:400", confidence_score_base: 0.5, eli5: "Swiss cheese might use animal rennet, so check the ingredients." },
  
  // ============ ADDITIONAL ADDITIVES ============
  stearic_acid: { name: "stearic_acid", aliases: ["e570", "octadecanoic_acid"], halal_alternatives: ["plant_based_stearic_acid", "vegetable_stearic_acid"], conversion_ratio: "1:1", category: "additive", status: "questionable", school_of_thought_variation: {}, inheritance: [], notes: "Can be animal or plant-derived. Must be plant-based", quranic_reference: "Surah Al-Baqarah 2:173", hadith_reference: "Sahih Muslim 13:3808", confidence_score_base: 0.5, eli5: "Stearic acid can come from animals, so check for plant-based versions." },
  palmitic_acid: { name: "palmitic_acid", aliases: ["hexadecanoic_acid"], halal_alternatives: ["plant_based_palmitic_acid"], conversion_ratio: "1:1", category: "additive", status: "questionable", school_of_thought_variation: {}, inheritance: [], notes: "Fatty acid that can be animal or plant-derived", quranic_reference: "Surah Al-Baqarah 2:173", hadith_reference: "Sahih Muslim 13:3808", confidence_score_base: 0.5, eli5: "This ingredient can come from animals, so check the source." },
  oleic_acid: { name: "oleic_acid", aliases: ["omega_9"], halal_alternatives: ["plant_based_oleic_acid"], conversion_ratio: "1:1", category: "additive", status: "questionable", school_of_thought_variation: {}, inheritance: [], notes: "Usually plant-derived but can be animal-sourced. Check label", quranic_reference: "Surah Al-Baqarah 2:172", hadith_reference: "Sahih Bukhari 7:67:400", confidence_score_base: 0.7, eli5: "Oleic acid usually comes from plants, but check the label to be sure." },
  beeswax: { name: "beeswax", aliases: ["e901", "yellow_wax"], halal_alternatives: ["carnauba_wax", "candellila_wax"], conversion_ratio: "1:1", category: "additive", status: "halal", school_of_thought_variation: {}, inheritance: [], notes: "Beeswax is generally considered halal. Used as food coating", quranic_reference: "Surah An-Nahl 16:68-69", hadith_reference: "", confidence_score_base: 0.9, eli5: "Beeswax comes from bees and is generally considered halal." },
  
  // ============ ADDITIONAL PROCESSED FOODS ============
  instant_noodles: { name: "instant_noodles", aliases: ["ramen_noodles", "cup_noodles"], halal_alternatives: ["halal_instant_noodles", "homemade_noodles"], conversion_ratio: "1:1", category: "processed_food", status: "haram", school_of_thought_variation: {}, inheritance: ["pork"], notes: "Seasoning packets often contain pork extract. Check for halal-certified brands", quranic_reference: "Surah Al-Baqarah 2:173", hadith_reference: "Sahih Bukhari 7:67:400", confidence_score_base: 0.1, eli5: "Instant noodles often contain pork flavoring in the seasoning packet." },
  frozen_pizza: { name: "frozen_pizza", aliases: ["ready_made_pizza", "premade_pizza"], halal_alternatives: ["halal_frozen_pizza", "homemade_pizza"], conversion_ratio: "1:1", category: "processed_food", status: "haram", school_of_thought_variation: {}, inheritance: ["pork"], notes: "Often contains pepperoni or pork. Check ingredients carefully", quranic_reference: "Surah Al-Baqarah 2:173", hadith_reference: "Sahih Muslim 13:3808", confidence_score_base: 0.1, eli5: "Frozen pizza often contains pork toppings like pepperoni." },
  hot_pockets: { name: "hot_pockets", aliases: ["microwave_pastries", "frozen_sandwiches"], halal_alternatives: ["halal_hot_pockets", "homemade_pastries"], conversion_ratio: "1:1", category: "processed_food", status: "haram", school_of_thought_variation: {}, inheritance: ["pork"], notes: "Often contains pepperoni or pork sausage. Check ingredients", quranic_reference: "Surah Al-Baqarah 2:173", hadith_reference: "Sahih Muslim 13:3808", confidence_score_base: 0.1, eli5: "Hot pockets often contain pork products like pepperoni or sausage." },
  frozen_burritos: { name: "frozen_burritos", aliases: ["ready_burritos", "premade_burritos"], halal_alternatives: ["halal_frozen_burritos", "homemade_burritos"], conversion_ratio: "1:1", category: "processed_food", status: "haram", school_of_thought_variation: {}, inheritance: ["pork"], notes: "Often contains pork or lard. Check for halal-certified versions", quranic_reference: "Surah Al-Baqarah 2:173", hadith_reference: "Sahih Muslim 13:3808", confidence_score_base: 0.1, eli5: "Frozen burritos often contain pork or pork fat." },
  beef_jerky: { name: "beef_jerky", aliases: ["jerky", "dried_meat"], halal_alternatives: ["halal_beef_jerky", "turkey_jerky_halal"], conversion_ratio: "1:1", category: "meat", status: "questionable", school_of_thought_variation: {}, inheritance: [], notes: "Must be halal-certified. Often contains non-halal meat", quranic_reference: "Surah Al-Baqarah 2:172", hadith_reference: "Sahih Bukhari 7:67:400", confidence_score_base: 0.7, eli5: "Beef jerky must be from halal-certified beef." },
  
  // ============ ADDITIONAL DESSERTS ============
  creme_brulee: { name: "creme_brulee", aliases: ["burnt_cream", "custard_dessert"], halal_alternatives: ["halal_creme_brulee", "homemade_creme_brulee"], conversion_ratio: "1:1", category: "dessert", status: "questionable", school_of_thought_variation: {}, inheritance: ["vanilla_extract"], notes: "Check vanilla source (may contain alcohol)", quranic_reference: "Surah Al-Baqarah 2:172", hadith_reference: "Sahih Muslim 10:3893", confidence_score_base: 0.7, eli5: "Crème brûlée might contain vanilla extract with alcohol, so check the ingredients." },
  ice_cream_alcohol: { name: "ice_cream_alcohol", aliases: ["alcoholic_ice_cream", "ice_cream_with_liqueur"], halal_alternatives: ["halal_ice_cream", "non_alcoholic_ice_cream"], conversion_ratio: "1:1", category: "dessert", status: "haram", school_of_thought_variation: {}, inheritance: ["alcohol"], notes: "Some premium ice creams contain alcohol. Avoid all varieties with alcohol", quranic_reference: "Surah Al-Ma'idah 5:90", hadith_reference: "Sahih Muslim 10:3893", confidence_score_base: 0.1, eli5: "Some ice cream contains alcohol, which is forbidden." },
  chocolate_truffles: { name: "chocolate_truffles", aliases: ["truffles", "chocolate_confections"], halal_alternatives: ["halal_chocolate_truffles", "truffles_without_liqueur"], conversion_ratio: "1:1", category: "dessert", status: "questionable", school_of_thought_variation: {}, inheritance: ["alcohol"], notes: "May contain liqueur fillings. Check ingredients or make halal version", quranic_reference: "Surah Al-Ma'idah 5:90", hadith_reference: "Sahih Muslim 10:3893", confidence_score_base: 0.5, eli5: "Some chocolate truffles contain alcohol, so check the ingredients." },
  
  // ============ ADDITIONAL FLAVORINGS ============
  artificial_flavoring: { name: "artificial_flavoring", aliases: ["natural_flavoring", "artificial_flavor"], halal_alternatives: ["halal_certified_flavoring", "plant_based_flavors"], conversion_ratio: "1:1", category: "flavoring", status: "questionable", school_of_thought_variation: {}, inheritance: [], notes: "May contain alcohol carriers or meat-based flavors. Check for halal-certified", quranic_reference: "Surah Al-Baqarah 2:173", hadith_reference: "Sahih Muslim 13:3808", confidence_score_base: 0.5, eli5: "Artificial flavoring might contain alcohol or meat, so check for halal versions." },
  msg: { name: "msg", aliases: ["monosodium_glutamate", "e621"], halal_alternatives: ["halal_certified_msg", "seaweed_extract"], conversion_ratio: "1:1", category: "flavoring", status: "halal", school_of_thought_variation: {}, inheritance: [], notes: "Generally halal if derived from plant sources or fermentation. Check source", quranic_reference: "Surah Al-Baqarah 2:172", hadith_reference: "", confidence_score_base: 0.9, eli5: "MSG is usually halal if it comes from plants or fermentation." },
};

console.log(`Generated ${Object.keys(comprehensiveIngredients).length} comprehensive ingredient entries`);

// Convert to flat format for halal_knowledge.json
const flatKnowledge = {};
Object.entries(comprehensiveIngredients).forEach(([key, value]) => {
  // Build references array
  const references = [];
  if (value.quranic_reference) references.push(value.quranic_reference);
  if (value.hadith_reference) references.push(value.hadith_reference);
  
  flatKnowledge[key] = {
    status: value.status,
    inheritance: value.inheritance || [],
    alternatives: value.halal_alternatives || [],
    notes: value.notes || "",
    references: references,
    aliases: value.aliases || [],
    confidence_score_base: value.confidence_score_base || 0.5,
    eli5: value.eli5 || "",
    // Enhanced fields
    category: value.category,
    school_of_thought_variation: value.school_of_thought_variation || {},
    conversion_ratio: value.conversion_ratio || "1:1",
    flavor_role: value.flavor_role || "",
    cuisine: value.cuisine || ""
  };
});

// Write flat structure
fs.writeFileSync(outputFlatPath, JSON.stringify(flatKnowledge, null, 2), 'utf8');
console.log(`✅ Created enhanced halal_knowledge.json with ${Object.keys(flatKnowledge).length} entries`);

// Validate JSON
try {
  JSON.parse(fs.readFileSync(outputFlatPath, 'utf8'));
  console.log('✅ JSON validation: PASSED');
} catch (e) {
  console.error('❌ JSON validation: FAILED', e.message);
  process.exit(1);
}

console.log('\n✅ Next step: Run convertToNestedJson.cjs to generate nested ingredients.json');
